blank_issues_enabled: false
contact_links:
  - name: Upstream GraphViz
    url: https://www.graphviz.org/
    about: 'If you want to report anything to the upstream GraphViz project, see also the GraphViz website:'
